CLANG_BIN=/usr/local/google/home/usx/build/bin/clang++ \
DEB_LIB_PCM=$(mktemp) \
ANOTHER_LIB_PCM=$(mktemp) \
ANOTHER_LIB_PCM2=$(mktemp) \
&& \
${CLANG_BIN} \
-fno-exceptions \
-funsigned-char \
-fnew-alignment=8 \
-fcoro-aligned-allocation \
-fmodule-name=deb_lib \
-Xclang=-fmodule-map-file-home-is-cwd \
-xc++ \
-Xclang=-emit-module \
-pthread \
-std=gnu++20 \
-c \
module_reproducer/deb_lib.cppmap \
-o \
${DEB_LIB_PCM} \
&& \
${CLANG_BIN} \
-iquote \
. \
-fno-exceptions \
-funsigned-char \
-fnew-alignment=8 \
-fcoro-aligned-allocation \
-fmodule-name=another_lib \
-Xclang=-fmodule-map-file-home-is-cwd \
-xc++ \
-Xclang=-emit-module \
-Xclang=-fmodule-file=${DEB_LIB_PCM} \
-pthread \
-std=gnu++20 \
-c \
module_reproducer/another_lib.cppmap \
-o \
${ANOTHER_LIB_PCM} \
&& \
${CLANG_BIN} \
-iquote \
. \
-fno-exceptions \
-funsigned-char \
-fnew-alignment=8 \
-fcoro-aligned-allocation \
-fmodule-name=another_lib2 \
-Xclang=-fmodule-map-file-home-is-cwd \
-xc++ \
-Xclang=-emit-module \
-Xclang=-fmodule-file=${ANOTHER_LIB_PCM} \
-pthread \
-std=gnu++20 \
-c \
module_reproducer/another_lib2.cppmap \
-o \
${ANOTHER_LIB_PCM2} \
&& \
${CLANG_BIN} \
-iquote \
. \
-fno-exceptions \
-funsigned-char \
-fnew-alignment=8 \
-fcoro-aligned-allocation \
-Xclang=-fmodule-file=${ANOTHER_LIB_PCM2} \
-pthread \
-std=gnu++20 \
module_reproducer/test_lib.cc